version: '3.9'

services:
  go-api:
    container_name: go-api
    image: k00kie/go-api
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports: 
      - "8008:8008"
    depends_on:
      - go_db
    
  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    #command: psql -U postgres -d postgres < docker-entrypoint-initdb.d/data.sql

volumes:
  pgdata:
  
